---
version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    ignore:
      # Peer dependencies of Cargo
      - dependency-name: semver
      - dependency-name: crates-io
    rebase-strategy: disabled

  - package-ecosystem: npm
    directory: /test/cdk
    schedule:
      interval: daily
    rebase-strategy: disabled
