[package]
name = "cfn-mig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.54.1"
aws-sdk-cloudformation = "0.24.0"
dialoguer = "0.10.3"
tokio = { version = "1", features = ["full"] }
