[package]
name = "cfn-resource-migrator"
version = "0.1.0"
edition = "2021"
description = "A command line tool which can migrate CloudFormation resources between stacks"
license = "Apache-2.0"
homepage = "https://github.com/udondan/cfn-resource-migrator/"
repository = "https://github.com/udondan/cfn-resource-migrator/"
authors = ["Daniel Schroeder"]
readme = "README.md"
keywords = ["aws", "cfn", "CloudFormation", "migration", "resources"]
categories = ["command-line-utilities"]
publish = false

[dependencies]
aws-config = "0.54.1"
aws-sdk-cloudformation = "0.24.0"
dialoguer = "0.10.3"
serde_json = "1.0.66"
tokio = { version = "1", features = ["full"] }

[dependencies.uuid]
version = "1.3.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
]
