[package]
name = "cfn-teleport"
version = "0.3.0"
edition = "2021"
description = "Moves CloudFormation resources between stacks"
license = "Apache-2.0"
homepage = "https://github.com/udondan/cfn-teleport/"
repository = "https://github.com/udondan/cfn-teleport/"
authors = ["Daniel Schroeder"]
readme = "README.md"
keywords = ["aws", "cfn", "CloudFormation", "migration", "resources"]
categories = ["command-line-utilities"]
publish = true

[dependencies]
atty = "0.2.14"
aws-config = "0.55.0"
aws-sdk-cloudformation = "0.25.1"
clap = { version = "4.2.1", features = ["derive"] }
console = "0.15.5"
dialoguer = "0.10.4"
serde_json = "1.0.95"
spinners = "4.1.0"
tokio = { version = "1", features = ["full"] }

[dependencies.uuid]
version = "1.3.1"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
]
