pre_bump_hooks = [
    "echo {{version}}",
#    "cargo test",
#    "cargo clippy",
#    "cargo build --release",
#    "cargo fmt --all",
#    "cargo bump {{version}}",
]

post_bump_hooks = [
    "git push",
    "git push origin {{version}}",
]

tag_prefix = "v"

ignore_merge_commits = true

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "cfn-teleport"
owner = "udondan"
authors = [
  { username = "udondan", signature = "Daniel Schroeder"}
]
