---
# Based on https://github.com/nicolas-van/rust-cross-compile-example - Thanks!

name: Testing homebrew mr

on:
  pull_request: # for testing, when we change the workflow
    branches:
      - main

jobs:
  homebrew-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: udondan/homebrew-software
          token: ${{ secrets.OVERRIDE_TOKEN }}

      - name: Update homebrew formula
        run: |
          VERSION="${GITHUB_REF_NAME}"
          if ! [[ "${VERSION}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            VERSION="1.2.3"
          fi

          SHA1=($(shasum -a 256 Cargo.lo*))

          echo "${TEMPLATE}" | sed \
            -e "s!{{ version }}!${VERSION:1}!g" \
            -e 's!{{ intel_url }}!A!g' \
            -e 's!{{ intel_sha }}!B!g' \
            -e 's!{{ arm_url }}!C!g' \
            -e 's!{{ arm_sha }}!D!g' \
            > cfn-teleport.rb
          cat cfn-teleport.rb
          shasum -a 256 *
          git status
          git diff
        env:
          TEMPLATE: |
            # typed: false
            # frozen_string_literal: true

            class CfnTeleport < Formula
              desc "A command line-tool which can migrate CloudFormation resources between stacks"
              homepage "${{ github.server_url }}/${{ github.repository }}"
              version "{{ version }}"
              license "Apache-2.0"

              if OS.mac? && Hardware::CPU.intel?
                url "{{ intel_url }}"
                sha256 "{{ intel_sha }}"
              end
              if OS.mac? && Hardware::CPU.arm?
                url "{{ arm_url }}"
                sha256 "{{ arm_sha }}"
              end

              def install
                bin.install "cfn-teleport"
              end
            end
