---
# Based on https://github.com/nicolas-van/rust-cross-compile-example - Thanks!

name: Testing homebrew mr

on:
  pull_request: # for testing, when we change the workflow
    branches:
      - main

jobs:
  homebrew-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Update homebrew formula
        run: |
          echo "${TEMPLATE}" | sed \
            -e 's!{{ version }}!1.2.3!g' \
            -e 's!{{ intel_url }}!A!g' \
            -e 's!{{ intel_sha }}!B!g' \
            -e 's!{{ arm_url }}!C!g' \
            -e 's!{{ arm_sha }}!D!g' \
            > cfn-teleport.rb
          cat cfn-teleport.rb
          shasum -a 256 *
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          GH_EVENT: ${{ github.event_name }}
          TEMPLATE: |
            # typed: false
            # frozen_string_literal: true

            class CfnTeleport < Formula
              desc "A command line-tool which can migrate CloudFormation resources between stacks"
              homepage "${{ github.server_url }}/${{ github.repository }}"
              version "{{ version }}"
              license "Apache-2.0"

              if OS.mac? && Hardware::CPU.intel?
                url "{{ intel_url }}"
                sha256 "{{ intel_sha }}"
              end
              if OS.mac? && Hardware::CPU.arm?
                url "{{ arm_url }}"
                sha256 "{{ arm_sha }}"
              end

              def install
                bin.install "cfn-teleport"
              end
            end
