---
# Based on https://github.com/nicolas-van/rust-cross-compile-example - Thanks!

name: Publish

on:
  release:
    types:
      - published
  workflow_dispatch:
  pull_request: # for testing, when we change the workflow
    branches:
      - main
    paths:
      - .github/workflows/publish.yml

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    # necessary for windows
    shell: bash

jobs:
  chocolatey-publish:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Generate chocolatey package
        run: |
          if (-not $Env:NUSPEC) {
            Write-Error "NUSPEC variable not set"
            exit 1
          }

          $markdown = Get-Content -Path "CHANGELOG.md" -Raw
          $startIndex = $markdown.IndexOf("## [", 0)
          $endIndex = $markdown.IndexOf("## [", $startIndex + 1)
          $releaseNotes = $markdown.Substring($startIndex, $endIndex - $startIndex)

          $nuspec = $Env:NUSPEC
          $installScript = $Env:INSTALL_SCRIPT

          $version = $Env:GITHUB_REF_NAME -replace '^v', ''
          if ($version -notmatch '^\d+\.\d+\.\d+$') {
            $version = '0.4.0'
          }

          # Get the SHA256 hashes
          $sha32 = "6fc3b8421144d046dd6b5fc83978b468a23c748f5357d2be381a4d963551d385"
          $sha64 = "8081970e7a240b2b559a042e4a1e3149001a9280bb752b954db7302f6ee380b9"

          # Build the URLs
          $url32 = "https://github.com/udondan/cfn-teleport/releases/download/{0}/cfn-teleport-i686-pc-windows-msvc-v{0}.exe" -f $version
          $url64 = "https://github.com/udondan/cfn-teleport/releases/download/{0}/cfn-teleport-x86_64-pc-windows-msvc-v{0}.exe" -f $version

          # Replace the placeholders in the nuspec and script files
          $nuspecContent = $nuspec.Replace('{{ url32 }}', $url32).Replace('{{ sha32 }}', $sha32).Replace('{{ url64 }}', $url64).Replace('{{ sha64 }}', $sha64).Replace('{{ version }}', $version).Replace('{{ release_notes }}', $releaseNotes)
          $installScriptContent = $installScript.Replace('{{ url32 }}', $url32).Replace('{{ sha32 }}', $sha32).Replace('{{ url64 }}', $url64).Replace('{{ sha64 }}', $sha64).Replace('{{ version }}', $version)

          # Write nuspec and script files
          $nuspecPath = "${{ github.workspace }}/cfn-teleport.nuspec"
          Set-Content -Path $nuspecPath -Value $nuspecContent

          $toolsDir = "${{ github.workspace }}/tools"
          New-Item -ItemType Directory -Force -Path $toolsDir
          $installScriptPath = "${{ github.workspace }}/tools/chocolateyInstall.ps1"
          Set-Content -Path $installScriptPath -Value $installScriptContent

          # Output file content
          echo "#### cfn-teleport.nuspec ####"
          echo "$nuspecContent"
          echo "#### chocolateyInstall.ps1 ####"
          echo "$installScriptContent"

          # Create package
          echo "Creating package..."
          choco pack $nuspecPath

          #if ("${{ github.event_name }}" -ne "pull_request") {
            # Test installation
            echo "Installing package..."
            $nupgkFile = "${{ github.workspace }}/cfn-teleport.{0}.nupkg" -f $version
            choco install cfn-teleport --source $nupgkFile --yes --version $version

            # Check if installation was successful
            echo "Checking if package was installed..."
            Get-Command cfn-teleport
            cfn-teleport.exe --version

            # Uninstall package
            echo "Uninstalling package..."
            choco uninstall cfn-teleport --yes

            # Ensure package is uninstalled
            echo "Checking if package was uninstalled..."
            if (Get-Command cfn-teleport -ErrorAction SilentlyContinue) {
              Write-Error "Package was not uninstalled"
              exit 1
            }

            # Push package
            echo "Pushing package..."
            #choco push $nupgkFile --source https://push.chocolatey.org/ --api-key ${{ secrets.CHOCOLATEY_API_KEY }}
          #}
        env:
          NUSPEC: |
            <?xml version="1.0"?>
            <package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
              <metadata>
                <id>cfn-teleport</id>
                <title>cfn-teleport</title>
                <version>{{ version }}</version>
                <authors>udondan</authors>
                <description>A command-line tool which can move CloudFormation resources between stacks</description>
                <summary>A command-line tool which can move CloudFormation resources between stacks</summary>
                <tags>aws cloudformation migration</tags>
                <licenseUrl>https://github.com/udondan/cfn-teleport/blob/master/LICENSE</licenseUrl>
                <projectUrl>https://github.com/udondan/cfn-teleport</projectUrl>
                <packageSourceUrl>https://github.com/udondan/cfn-teleport/blob/main/.github/workflows/publish.yml</packageSourceUrl>
                <releaseNotes>{{ release_notes }}</releaseNotes>
              </metadata>
              <files>
                <file src="tools\**" target="tools" />
              </files>
            </package>
          INSTALL_SCRIPT: |
            $packageName = 'cfn-teleport'
            $version = '{{ version }}'
            $installDir = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"

            $fileArgs = @{
              packageName    = $packageName
              fileFullPath   = Join-Path $installDir 'cfn-teleport.exe'
              url            = '{{ url32 }}'
              checksum       = '{{ sha32 }}'
              url64bit       = '{{ url64 }}'
              checksum64     = '{{ sha64 }}'
              checksumType   = 'sha256'
              ChecksumType64 = 'sha256'
            }
            Get-ChocolateyWebFile @fileArgs
