---
name: Release Automerge

on:
  schedule:
    - cron: 0 18 * * 0
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-latest-release:
    runs-on: ubuntu-latest
    steps:
      - name: Find Pull Request
        uses: juliangruber/find-pull-request-action@v1.8.0
        id: find-pull-request
        with:
          branch: release-please--branches--main--components--cfn-teleport

      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v2.0.4
        with:
          github-token: ${{ secrets.OVERRIDE_TOKEN }}
          number: ${{ steps.find-pull-request.outputs.number }}
        if: ${{ steps.find-pull-request.outputs.number != '' }}

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1.2.0
        with:
          github-token: ${{ secrets.OVERRIDE_TOKEN }}
          number: ${{ steps.find-pull-request.outputs.number }}
          method: squash
        if: ${{ steps.find-pull-request.outputs.number != '' }}
