---
# Based on https://github.com/rust-embedded/cargo-binutils/blob/master/.github/workflows/ci.yml - Thanks!
name: Test

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
        os: [ubuntu-latest, macos-latest, windows-latest]
        experimental: [false]
        include:
          - rust: nightly
            os: ubuntu-latest
            experimental: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: llvm-tools-preview

      - name: Run tests
        run: cargo test --verbose

      - name: Build and install
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path . -f

  conclusion:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Result
        run: exit 0
